### ISSUE TITLE
[JS, HTML] Add event listener to the arrow divs in the landing page & add buttons in the responsive design

### ISSUE THREAD

**Issue by shamskhodary** [GSG-CF05/GAMSIC#34]
## In the landing page, we will work on the following:

- Add event listener to the arrow divs to navigate between the pages.
- The function executes when the user click on any part of the arrow background facilitating the user navigation.
- Add two new buttons to the responsive design below the images.

**Comment by Bas-Shiekh** [comment]
the task completion took 1 hour
