### ISSUE TITLE
[HTML, CSS] Music Home Page

### ISSUE THREAD

**Issue by shamskhodary** [GSG-CF05/GAMSIC#6]
## This page contains the following:

* One photo.
* Title.
* Subtitle.
* Paragraph.
* Button.

--- 

## UI:

![Music Home Page - Dark](https://user-images.githubusercontent.com/47992412/159042390-0a82dc2f-2b13-4fb5-adaa-d11221538148.png)

**Comment by moustf** [comment]
This task took less than 3 hours but more than 2 and a half because I underestimated the time needed.
